### ISSUE TITLE
HC Table Improvements

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#13]
> could you please also fix this table https://csis.myclimateservice.eu/study/25/step/3681/view/table?

> The most important information in this table is hidden in the “event description” and most of the columns are the same for the whole table. My proposal here:
> 1) Write split the “event description” in two fields and make them understandable for the users. One part is some kind of a temperature, the other is some kind of a frequency information, but even  don’t really understand what they mean.
> 2) Get the information that is the same for all rows out of the table and into the table name or description. At least the Urban area & Country. Temp95 Perz too.
> 3) Hide the information that is of no use for the users. Oid???

**Comment by humerh** [comment]
Is the REST-Interface of emikat responsible also for the representation / formating of data in drupal????
It is possible from CSIS-side to exclude columns and it is also possible to rename header columns.

My picture is, that the task of optimising of the representation (multi language support, context sensitive formating) should be done on CSIS side and not on emikat side.

**Comment by p-a-s-c-a-l** [comment]
@humerh 

> Is the REST-Interface of emikat responsible also for the representation / formating of data in drupal????

no

> My picture is, that the task of optimising of the representation (multi language support, context sensitive formating) should be done on CSIS side and not on emikat side.

Yes, you are absolutely right, this is something that has to be done on **user interface** side. We are addressing this in table component, no need for you to change anything in EMAIKT APIs.

**Comment by RobAndGo** [comment]
Is the issue here about what the table is showing @claudiahahn? If so, then here is a brief explanation.

For the grid point of Vienna, the heat wave (HW) events corresponding to:
- rare (1 event in 20 years)
- occasional (1 event in 5 years)
- frequent (1 event per year)
 are shown in the 3rd column from the right.

The second column from the right shows what these events are with format:
XX.X_Y.YYYd
where
XX.X is the threshold for the maximum daily temperature in °C
and
Y.YYYd is the duration (or number of consecutive days), where the threshold temperature is reached or exceeded. This value is an average per year, which explains the fraction of a day.

So, for example, on the second page of values, for the emissions scenario for RCP4.5 and future time period of 2041-2070, the "Frequent" event is defined with "34.5_2.533d". This means that heat waves of duration 2.533 days per year with a daily maximum temperature exceeding 34.5°C would be a frequent event, i.e. occur once per year. An occasional event for the RCP4.5 scenario and 2041-2070 is "36_0.633d" meaning an event of 0.633d per year with a daily maximum temperature exceeding 36.0C. 

The last columns shows the 95th percentile of the daily maximum temperature, and is used in the mortality calculation for PLINIVS. The idea is that any temperature above this 95th percentile will lead to mortality, with the greater the difference leading to a higher mortality rate.

**Comment by claudiahahn** [comment]
since it is about the table improvements and @DenoBeno 's question about the "event description" column was copied in here, I thought it would fit. Thanks @RobAndGo

**Comment by p-a-s-c-a-l** [comment]
O.K. Any why is duration and 95th percentile missing in the table blow: @humerh @RobAndGo 

![grafik](https://user-images.githubusercontent.com/1788226/83244298-6f748280-a19f-11ea-8af7-ba109646f765.png)

[EMIKAT API Request](https://service.emikat.at/EmiKatTst/api/scenarios/3209/feature/tab.CLY_HAZARD_EVENTS_STUDY.2036/table/data?rownum=1000&column=Latitude&column=Longitude&column=Hazard%20Event%20Type&column=EMISSIONS_SCENARIO&column=TIME_PERIOD&column=EVENT_FREQUENCY&column=Event%20Descriptor&column=Temp95Perz)

**Comment by RobAndGo** [comment]
For the "RAIN" events, only the amount is important. The duration is always 1 day and there is no 95th percentile calculated. That is, the 95th percentile for precipitation can be left blank.

**Comment by p-a-s-c-a-l** [comment]
OK, and what's the unit of the amount? mm? l/m²

**Comment by RobAndGo** [comment]
Yes, it is mm (which is the same as l/m²)

**Comment by p-a-s-c-a-l** [comment]
This is how the table now looks like: 

![grafik](https://user-images.githubusercontent.com/1788226/83259319-1cf39000-a1b8-11ea-9208-a79112c683fd.png)

**Comment by p-a-s-c-a-l** [comment]
done
